cloud_id                 = "b1gfos8gdrr9vdpjnj2r"
folder_id                = "b1gk972uam08fn7uv33e"
zone                     = "ru-central1-a"
image_id                 = "fd88u4ib1haq1rrkn8qp"
public_key_path          = "~/.ssh/appuser.pub"
subnet_id                = "e9bslbc453l2r4dllidk"
service_account_key_file = "./key.json"
private_key_path         = "~/.ssh/appuser"